import React from 'react';


const products = [
  {
    id: 1,
    name: "Luxurious Elixir Rough",
    price: 220,
    size: "100ml",
    rating: 4.9,
    reviews: 624,
    img: 'Fash.png',
  },
  {
    id: 2,
    name: "The Golden Legacy",
    price: 160,
    size: "100ml",
    rating: 4.8,
    reviews: 520,
    img: 'Lux.png',
  },
  {
    id: 3,
    name: "Luxurious Elixir",
    price: 250,
    size: "150ml",
    rating: 5.0,
    reviews: 711,
    img: 'P3.png',
  },
  {
    id: 4,
    name: "Luxurious Essence",
    price: 200,
    size: "100ml",
    rating: 4.7,
    reviews: 121,
    img: 'P4.png',
  },
  {
    id: 5,
    name: "Luxurious Essence",
    price: 220,
    size: "100ml",
    rating: 4.7,
    reviews: 121,
    img: 'P5.png',
  },
  {
    id: 6,
    name: "Luxurious Essence",
    price: 120,
    size: "100ml",
    rating: 4.7,
    reviews: 121,
    img: 'P6.png',
  },
  {
    id: 7,
    name: "Luxurious Essence",
    price: 200,
    size: "100ml",
    rating: 4.7,
    reviews: 121,
    img: 'P7.png',
  },
  {
    id: 8,
    name: "Luxurious Essence",
    price: 200,
    size: "100ml",
    rating: 4.7,
    reviews: 121,
    img: 'P8.png',
  },
  {
    id: 9,
    name: "Luxurious Essence",
    price: 200,
    size: "100ml",
    rating: 4.7,
    reviews: 121,
    img: 'P9.png',
  },
  {
    id: 10,
    name: "Luxurious Essence",
    price: 200,
    size: "100ml",
    rating: 4.7,
    reviews: 121,
    img: 'P10.png',
  },
  {
    id: 11,
    name: "Luxurious Essence",
    price: 100,
    size: "80ml",
    rating: 4.7,
    reviews: 121,
    img: 'P11.png',
  },
  {
    id: 12,
    name: "Luxurious Essence",
    price: 240,
    size: "90ml",
    rating: 4.7,
    reviews: 121,
    img: 'P12.png',
  }
];

export default products;